# Site settings
title: Patrick Michelberger
email: patrick.michelberger@tum.de
description: ""  
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://patrick.michelberger.info" # the base hostname & protocol for your site
twitter_username: pmichelberger
github_username:  pmichelberger

# Build settings
markdown: kramdown
